apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility
  template:
    metadata:
      labels:
        app: utility
    spec:
      containers:
      - name: utility-simulator
        image: utility-producer:latest
        imagePullPolicy: Never
        env:
        - name: MQTT_BROKER
          value: "mqtt-service"
        - name: MQTT_PORT
          value: "1883"